<?php

namespace AppBundle\Repository;

/**
 * GroupaccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupaccountRepository extends \Doctrine\ORM\EntityRepository
{
}
