<?php

namespace AppBundle\Repository;

/**
 * MediatekMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediatekMediaRepository extends \Doctrine\ORM\EntityRepository
{
}
