<?php

namespace AppBundle\Repository;

/**
 * MediatekmediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediatekmediaRepository extends \Doctrine\ORM\EntityRepository
{
}
