<?php

namespace AppBundle\Repository;

/**
 * MediatekUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediatekUserRepository extends \Doctrine\ORM\EntityRepository
{
}
