<?php

namespace AppBundle\Repository;

/**
 * MediatekRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediatekRepository extends \Doctrine\ORM\EntityRepository
{
}
