<?php

namespace AppBundle\Repository;

/**
 * MediatekGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediatekGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
